from enum import Enum # Import Enum

class OrderAction(Enum):
    BUY = "BUY"
    SELL = "SELL"
    UNKNOWN = "UNKNOWN"

class OrderStatus(Enum):
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    PENDING_SUBMIT = "PENDING_SUBMIT"
    PENDING_CANCEL = "PENDING_CANCEL"
    PRE_SUBMITTED = "PRE_SUBMITTED"
    SUBMITTED = "SUBMITTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"
